test_position_trajectory_controller:
  ros__parameters:

    controller_name: "position_trajectory_controller"
    wait_sec_between_publish: 6
    check_starting_point: False

    goal_names: ["pos1", "pos2", "pos3"]
    pos1:
      positions: [0.]
      velocities: [0.]
    pos2:
      positions: [1.]
      velocities: [0.]
    pos3:
      positions: [0.]
      velocities: [0.]

    joints:
      - left_joint_a7
      
